# SUMMARY

**Tensor** is a set of primitive values shaped into any array any dimensions. Rank of tensor is number of dimensions.

TensorFlow Core programs as consisting of two discrete sections:

1. Building the computational graph
2. Running the computational graph

A **computational graph** is a series of TensorFlow operations arranged into a graph of nodes
 
To actually **evaluate** the nodes, we must run the computational graph within a session. A **session** encapsulates the control and state of the TensorFlow runtime

In [1]:
import tensorflow as tf
import numpy as np
sess = tf.Session()
sess = tf.InteractiveSession()
#The only difference with a regular Session is that an InteractiveSession installs itself as the default 
#session on construction. The methods Tensor.eval() and Operation.run() will use that session to run ops.

#### Syntaxis

In [73]:
a = tf.constant(3.154); b = tf.constant(2.1)      #constants
c = tf.add(a,b)             #addition
c = a + b                   #addition (also)

d = tf.placeholder(tf.float32, [None, 4]) #we promise to fill it)
print "placeholder example:\n{}\n".format(sess.run(d, feed_dict={d:[[1,2,3,4],[5,56,7,8]]}))

var = tf.Variable([.3], tf.float32)               #variables
init = tf.global_variables_initializer()
sess.run(init)      #we should to init variables
print "variable var = {}".format(sess.run(var))

placeholder example:
[[  1.   2.   3.   4.]
 [  5.  56.   7.   8.]]

variable var = [ 0.30000001]


In [263]:
import tensorflow as tf

In [ ]:
#files = tf.train.match_filenames_once('gs://dkuzin/experiments/test-data/data*', name = "myFiles")
files = tf.constant([1,2,3,4,5,6,7,8,9])
WORKERS_NUM = 3
#aa = files.shape.num_elements()
num_splits = tf.cast(tf.minimum(5, 6), tf.int16)
files_split = tf.split(files, [3,3,4], num = 3)

#filename_queue = tf.train.string_input_producer(files, num_epochs=None, shuffle=True, 
#                       seed=None, shared_name=None, name=None)
#reader = tf.WholeFileReader()
#_, d = reader.read(filename_queue)
#coord = tf.train.Coordinator()

init = (tf.global_variables_initializer(), tf.local_variables_initializer())
sess = tf.InteractiveSession()
sess.run(init)


print files_split[0].eval(session = sess)
print len(files_split)
print files_split

print files.eval(session = sess)
#files = sorted(files)
WORKERS_NUM = 3
WORKER_NUMBER = 2

#files_to_process = chunks[WORKER_NUMBER]

#print chunks
#print 
#print files_to_process
#sess.close()

In [312]:
files = tf.constant([1,2,3,4,5,6,7,8,9], dtype=tf.float16)
files_split = tf.split_v(files, 3, axis=0)

sess = tf.InteractiveSession()
init = (tf.global_variables_initializer(), tf.local_variables_initializer())
sess.run(init)
print files.eval(session=sess)
print
print files_split

AttributeError: 'module' object has no attribute 'split_v'

In [250]:
files_split[0].eval(session=sess)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.], dtype=float16)

In [251]:
files.shape

TensorShape([Dimension(10)])

In [252]:
files.get_shape()

TensorShape([Dimension(10)])

In [1]:
import tensorflow as tf

files_names = tf.train.match_filenames_once('gs://dkuzin/experiments/test-data/data*',
                                                        name = "myFiles")
filename_queue = tf.train.string_input_producer(files_names,
                                               shuffle=True,
                                               num_epochs=2)
reader = tf.TextLineReader()
_ , value = reader.read(filename_queue)

col1,col2 = tf.decode_csv(value, 
            record_defaults=[[1],[1]], field_delim="\t")

featues = tf.stack([col1,col2]) 

BATCH_SIZE = 5
min_after_dequeue = 10 * BATCH_SIZE
capacity = 20 * BATCH_SIZE
data_batch, label_batch = tf.train.batch([col1,[col2]], batch_size=BATCH_SIZE, 
                                         capacity=capacity)



init = (tf.global_variables_initializer(), tf.local_variables_initializer())
sess = tf.InteractiveSession()
sess.run(init)

coord = tf.train.Coordinator()  #after session inicialisation
_ = tf.train.start_queue_runners(coord=coord)

In [144]:
data_batch.eval(session = sess)

array([ 8971, 10641,  7745,  8705,  2934], dtype=int32)

In [136]:
label_batch.eval(session = sess)

array([[180],
       [592],
       [279],
       [320],
       [168]], dtype=int32)

In [11]:
import tensorflow as tf
INPUT_PATTERN = "gs://dkuzin/experiments/test-data/data*txt"
files_names = tf.train.match_filenames_once(INPUT_PATTERN,
                                                        name = "myFiles")
to_process = tf.strided_slice(files_names, [2],[9999999999],[2]) #, strides=[1])

init = (tf.global_variables_initializer(), tf.local_variables_initializer())
sess = tf.InteractiveSession()
sess.run(init)

(None, None)

In [12]:
files_names.eval(session = sess)

array(['gs://dkuzin/experiments/test-data/data.txt',
       'gs://dkuzin/experiments/test-data/data1.txt',
       'gs://dkuzin/experiments/test-data/data2.txt',
       'gs://dkuzin/experiments/test-data/data3.txt',
       'gs://dkuzin/experiments/test-data/data4.txt',
       'gs://dkuzin/experiments/test-data/data5.txt',
       'gs://dkuzin/experiments/test-data/data6.txt',
       'gs://dkuzin/experiments/test-data/data7.txt',
       'gs://dkuzin/experiments/test-data/data8.txt',
       'gs://dkuzin/experiments/test-data/data9.txt'], dtype=object)

In [13]:
to_process.eval(session = sess)

array(['gs://dkuzin/experiments/test-data/data2.txt',
       'gs://dkuzin/experiments/test-data/data4.txt',
       'gs://dkuzin/experiments/test-data/data6.txt',
       'gs://dkuzin/experiments/test-data/data8.txt'], dtype=object)

In [14]:
gena = (x for x in range(10))

In [22]:
gena.next()

6

In [43]:
a = tf.constant(0.1, shape=(7,1))
init = tf.global_variables_initializer()
sess.run(init)      #we should to init variables

In [57]:
a.eval()

array([[ 0.1],
       [ 0.1],
       [ 0.1],
       [ 0.1],
       [ 0.1],
       [ 0.1],
       [ 0.1]], dtype=float32)

In [38]:
b.eval()

array([[  5.53999996],
       [  9.07999992],
       [ 12.61999989],
       [ 16.15999985],
       [ 20.05399895]], dtype=float32)

In [25]:
squares = tf.square([[1,2,3],[4,5,6]])       #square every value
print "squares : \n{}".format(sess.run(squares))

squares : 
[[ 1  4  9]
 [16 25 36]]


In [8]:
loss = tf.reduce_sum(squares, axis = None)     #reduce_sum function (there are reduce_min and others)
print "axis = None : {}".format(sess.run(loss))
loss = tf.reduce_sum(squares, axis = 0)
print "axis = 0 : {}".format(sess.run(loss))
loss = tf.reduce_sum(squares, axis = 1)
print "axis = 1 : {}".format(sess.run(loss))

axis = None : 91
axis = 0 : [17 29 45]
axis = 1 : [14 77]


In [9]:
reassign_variable = tf.assign(var, [777])    #reduceefine variable
sess.run(reassign_variable)

array([ 777.], dtype=float32)

In [10]:
#what is matmul?
aa = tf.constant([[1,2],[1,2],[1,2]])   #3x2  
bb = tf.constant([[1,2,3,4], [1,2,3,4]])  #2x4
cc = tf.matmul(aa,bb)
print sess.run(cc), '\n'  #3x4
print np.dot(sess.run(aa), sess.run(bb))   #3x4

#so, matmul in tensorflow is dot product in n dimension

[[ 3  6  9 12]
 [ 3  6  9 12]
 [ 3  6  9 12]] 

[[ 3  6  9 12]
 [ 3  6  9 12]
 [ 3  6  9 12]]


In [16]:
#example of softmax
l = [5.1,1.0,2.0]
print (sess.run(tf.nn.softmax(l)))
#it is the same as:
import math
exp_l = [math.exp(x) for x in l]
print([round(x/sum(exp_l),8) for x in exp_l])

[ 0.94195497  0.01561072  0.04243432]
[0.94195497, 0.01561071, 0.04243432]


In [13]:
#indexes of max element in tensor
tf.argmax([[10,20,100,50],[10,70,3,50]], axis = 1).eval()

array([2, 1])

In [228]:
#tf.cast casts a tensor to a new type
print tf.cast([True,False,True], tf.float32).eval()
print tf.cast([1.4,2.5,3.9], tf.int16).eval()

[ 1.  0.  1.]
[1 2 3]


In [231]:
#tf.equal compare 2 vectors (each element)
tf.equal([1,2,3,0], [1,2,10,10]).eval()

array([ True,  True, False, False], dtype=bool)

#### ML instruments

In [17]:
x = tf.placeholder(tf.float32); y = tf.placeholder(tf.float32)
W = tf.Variable([1000.], tf.float32)  #start value

loss = tf.reduce_sum(tf.square(W * x - y))
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)  #it will change variables

init = tf.global_variables_initializer()
sess.run(init)      #we should to init variables
for _ in xrange(25):
    _, loss_val = sess.run([train, loss], feed_dict = {x:[1,2,3],y:[9,8,7]})
    print round(loss_val), '\t',
print '\n', W.eval()

13908194.0 	7210030.0 	3737700.0 	1937644.0 	1004495.0 	520751.0 	269978.0 	139977.0 	72585.0 	37649.0 	19538.0 	10149.0 	5282.0 	2759.0 	1451.0 	773.0 	421.0 	239.0 	145.0 	96.0 	70.0 	57.0 	50.0 	47.0 	45.0 	
[ 3.55603719]


In [20]:
#initialization of tensor using normal distribution
tf.truncated_normal((2,2), mean=0.0, stddev=0.1).eval()

array([[ 0.03983005,  0.03020634],
       [-0.0760996 ,  0.0266649 ]], dtype=float32)

#### TensorBoard: Graph Visualization

In [215]:
#!python /home/dkuzin/tensorflow/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py
#!tensorboard --logdir=/tmp/tensorflow/mnist/logs/mnist_with_summaries --port 6006

**Tensorboard**

In [ ]:
def variable_summaries(var, scope_name='summaries'):
    """Attach a lot of summaries to a Tensor (for TensorBoard visualization)."""
    with tf.name_scope(scope_name):
        mean = tf.reduce_mean(var)
        tf.summary.scalar('mean', mean)
        with tf.name_scope('stddev'):
            stddev = tf.sqrt(tf.reduce_mean(tf.square(var - mean)))
        tf.summary.scalar('stddev', stddev)
        tf.summary.scalar('max', tf.reduce_max(var))
        tf.summary.scalar('min', tf.reduce_min(var))
        tf.summary.histogram('histogram', var)
variable_summaries(nce_biases, scope_name='biases_stat')
merged = tf.summary.merge_all()

session = tf.Session(graph=graph)
writer = tf.summary.FileWriter('./graphs', session.graph)
for step in 1000:
    if step%100 == 0:
        run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
        run_metadata = tf.RunMetadata()
        _, loss_val, summary = session.run([optimizer, loss, merged],
                                options=run_options, run_metadata=run_metadata)
        writer.add_run_metadata(run_metadata, 'step%d' % counter[i])
        writer.add_summary(summary, counter[i])
    else:
        if step%10 == 0:
            _, loss_val, summary = session.run([optimizer, loss, merged])
            writer.add_summary(summary, counter[i])
        else:
            #usual run
            _, loss_val = session.run([optimizer, loss])

**Timeline:**

https://stackoverflow.com/questions/37751739/tensorflow-code-optimization-strategy